#!/usr/bin/env python3
"""
etl/build_business_review_cache.py  (2026-09-26, Ahmed: "BU business review
page with BU filter and line filter ... comprehensive comments ... include
changes in IQVIA in terms of brand, competitor shares and growth").

Builds cache/business_review.json + cache/business_review.data.js
(window.BUSINESS_REVIEW_CACHE = {b64Data: gzip+base64}) for the
"BU Business Review" tab (js/bu-review.js). READ-ONLY over existing caches;
it never touches a source workbook and re-implements no business rule that
is not already defined elsewhere -- every metric below mirrors the page that
owns it:

  Sales      cache/sales.data.js      Official target, Tender rows excluded
                                      (Non-Tender convention), CHC BU = CHC line
                                      (CHC_SALES shown as its own line only).
  Execution  cache/records.data.js    js/analytics.js accumulate(): active rows,
                                      sick-leave-exempt rows excluded, prorated
                                      frequency when present.
  Coaching   cache/coaching.data.js   DM / DSM / Senior DM, activeHalfMonth.
  Field days cache/working_days.data.js DM_DSM tier.
  IQVIA      cache/iqvia.data.js      Market Intelligence rules: OTHER MARKET dm1
                                      rows excluded, Zeta = 'ZETA PHARM*',
                                      BU/line market = rows tagged with that
                                      BU/line (getBlendedBuShare), YTD = Jan..latest
                                      vs same months prior year. Brand market =
                                      the product's main DM1.

Comments are generated by explicit rules and tagged FACT / INTERPRETATION /
HYPOTHESIS per BUSINESS_REVIEW_FRAMEWORK.md section 2.

Run:  python etl/build_business_review_cache.py
"""
import base64, collections, datetime, difflib, gzip, json, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CACHE = os.path.join(ROOT, 'cache')
BR_DIR = os.path.join(ROOT, 'Business Review')   # *.xlsx are git-ignored (.gitignore)
MAP_XLSX = os.path.join(BR_DIR, 'Brand_IQVIA_Map.xlsx')
ACTIONS_XLSX = os.path.join(BR_DIR, 'BU_Review_Actions.xlsx')
SCHEMA_VERSION = 4  # v4 2026-09-26 (Priority 3): IQVIA MAT view, products per company, data-gaps box (v3: sell-in vs IQVIA, customers, actions)
_OLD_SV = 2  # v2 2026-09-26: FY landing, volume/price split, comment impact ranking, new-entrant flags, no hypotheses

# ---------------------------------------------------------------- thresholds
# Ahmed 2026-09-26: good execution = Coverage >= 90% AND Right Frequency > 80%.
TH = {
    'cov': 0.90, 'rf': 0.80, 'visit': 0.90, 'coachCov': 1.0, 'cpd': 7.0, 'cpdChcSales': 12.0,
    'field': 0.85, 'sales': 100.0, 'salesWatch': 90.0, 'minShare': 0.005,  # growth-rule 0.5%
}

# ---------------------------------------------------------------- org map
BU_LINES = collections.OrderedDict([
    ('CHC', ['CHC', 'CHC_SALES']),
    ('Cluster', ['CVM-I', 'CVM-II', 'ORTHO-I', 'ORTHO-II', 'PEDIA']),
    ('DIAB', ['DIAB-I', 'DIAB-II', 'DIAB-III', 'DIAB-IV']),
    ('GIT', ['GIT-I', 'GIT-II', 'GIT-III', 'Derma', 'NEUROSCIENCE']),
])
LINE_BU = {l: b for b, ls in BU_LINES.items() for l in ls}
ALL_LINES = [l for ls in BU_LINES.values() for l in ls]
TEAM_OF = {'CHC_SALES': 'CHC_Sales', 'Derma': 'DERMA', 'NEUROSCIENCE': 'Neuroscience'}
IQ_LINE_OF = {'CHC_SALES': 'CHC', 'NEUROSCIENCE': 'CNS'}
NOT_IN_BU_TOTAL = {'CHC_SALES'}   # dashboard rule: CHC BU = CHC line

def K(s):
    s = str(s or '').upper().replace('SALES', 'S').replace('NEUROSCIENCE', 'NEURO').replace('DIABETES', 'DIAB').replace('CNS', 'NEURO')
    return re.sub(r'[^A-Z]', '', s)
KEY2LINE = {K(l): l for l in ALL_LINES}


def load_b64(fname):
    raw = open(os.path.join(CACHE, fname), encoding='utf-8').read()
    m = re.search(r'b64Data"?\s*:\s*"([^"]+)"', raw)
    if not m:
        sys.exit(f'[business_review] ERROR: {fname} has no b64Data')
    return json.loads(gzip.decompress(base64.b64decode(m.group(1)))), raw


def log(msg):
    print(f'[business_review] {msg}', flush=True)


def div(a, b):
    return (a / b) if b else None


# ============================================================ 1. SALES
def build_sales():
    c, _ = load_b64('sales.data.js')
    L = c['lookups']['lines']; M = c['lookups']['months']; B = c['lookups']['brands']
    months = sorted(m for m in M if re.match(r'2026-\d\d$', m))
    last = months[-1]
    line_m = collections.defaultdict(lambda: collections.defaultdict(float))
    brand = collections.defaultdict(lambda: collections.defaultdict(float))
    for r in c['rows']:
        mask = r[17]
        if mask & 2:          # Tender excluded (Non-Tender convention)
            continue
        m = M[r[0]]
        if m not in months:
            continue
        ln = L[r[1]]
        if ln not in LINE_BU:
            continue
        if mask & 16:
            if mask & 64:
                key = 'S'
            elif mask & 32:
                key = 'O'
            else:
                key = 'W'
            line_m[ln][m + key] += r[21]
            line_m[ln][m + key + 'q'] += r[20]
            brand[(ln, B[r[2]])][m + key] += r[21]
        else:
            line_m[ln][m + 'A'] += r[19]
            line_m[ln][m + 'Aq'] += r[18]
            brand[(ln, B[r[2]])][m + 'A'] += r[19]
    del c
    out = {'months': months, 'last': last, 'lines': {}, 'brands': {}}
    for ln in ALL_LINES:
        x = line_m.get(ln, {})
        out['lines'][ln] = {
            'mA': [round(x.get(m + 'A', 0)) for m in months],
            'mO': [round(x.get(m + 'O', 0)) for m in months],
            'mS': [round(x.get(m + 'S', 0)) for m in months],
            'mW': [round(x.get(m + 'W', 0)) for m in months],
        }
        # Volume / price-mix split of the gap vs Official target, per month:
        # target price p = O / Oq; volume = (Aq - Oq) * p; price/mix = A - Aq * p
        # (volume + price/mix = A - O exactly). Months with a target value but
        # no target units go to 'other'.
        vol, prc, oth = [], [], []
        for m in months:
            A, O, Aq, Oq = x.get(m + 'A', 0), x.get(m + 'O', 0), x.get(m + 'Aq', 0), x.get(m + 'Oq', 0)
            if O and Oq:
                p = O / Oq
                vol.append(round((Aq - Oq) * p)); prc.append(round(A - Aq * p)); oth.append(0)
            else:
                vol.append(0); prc.append(0); oth.append(round(A - O) if O else 0)
        out['lines'][ln].update({'mVol': vol, 'mPrice': prc, 'mOther': oth})
    for (ln, b), x in brand.items():
        a = sum(x.get(m + 'A', 0) for m in months)
        o = sum(x.get(m + 'O', 0) for m in months)
        if a <= 0 and o <= 0:
            continue
        out['brands'].setdefault(ln, []).append({
            'brand': b, 'ytdA': round(a), 'ytdO': round(o),
            'lastA': round(x.get(last + 'A', 0)), 'lastO': round(x.get(last + 'O', 0)),
            'prevA': round(x.get(months[-2] + 'A', 0)) if len(months) > 1 else 0,
        })
    for ln in out['brands']:
        out['brands'][ln].sort(key=lambda r: -r['ytdA'])
    bm = collections.defaultdict(lambda: [0.0] * len(months)); blines = collections.defaultdict(set)
    for (ln, b), x in brand.items():
        blines[b].add(ln)
        if ln in NOT_IN_BU_TOTAL:
            continue
        for i, m in enumerate(months):
            bm[b][i] += x.get(m + 'A', 0)
    out['brandMonthly'] = {b: [round(v) for v in vals] for b, vals in bm.items()}
    out['brandLines'] = {b: sorted(v) for b, v in blines.items()}
    log(f'sales: {len(months)} months ({months[0]}..{last}), {sum(len(v) for v in out["brands"].values())} line-brands')
    return out


# ============================================================ 2. EXECUTION (records)
def build_execution():
    r, _ = load_b64('records.data.js')
    d, _ = load_b64('dashboard.data.js')
    dims = d['dimensions']
    F = {n: i for i, n in enumerate(r['fields'])}
    periods = dims['periods']; teams = dims['teams']; classes = dims['classes']
    resigned_idx = dims['statuses'].index('Resigned') if 'Resigned' in dims['statuses'] else -1
    team_line = {}
    for t in teams:
        ln = KEY2LINE.get(K(t))
        if ln:
            team_line[teams.index(t)] = ln
    is_a = [str(c).upper().startswith('A') for c in classes]
    Z = lambda: {'cov': 0, 'rf': 0, 'n': 0, 'vis': 0, 'tgt': 0, 'aRf': 0, 'aN': 0, 'act': set(), 'res': set(), 'below': 0, 'over': 0}
    g = collections.defaultdict(Z)
    fi = F
    for row in r['rows']:
        ln = team_line.get(row[fi['teamIdx']])
        if not ln:
            continue
        key = (ln, row[fi['periodIdx']])
        s = g[key]
        if row[fi['isActive']]:
            s['act'].add(row[fi['employeeIdx']])
            if row[fi['isExempt']]:
                continue
            pr = row[fi['proratedFrequency']] if row[fi['proratedFrequency']] is not None else -1
            vis = row[fi['visits']] or 0
            tgt = pr if pr >= 0 else (row[fi['frequency']] or 0)
            rf = (1 if vis >= pr else 0) if pr >= 0 else row[fi['rightFreq']]
            s['cov'] += row[fi['coveredDoctor']]; s['rf'] += rf; s['n'] += 1
            s['vis'] += vis; s['tgt'] += tgt
            if rf == 0:
                s['below'] += 1
            elif vis > tgt:
                s['over'] += 1
            ci = row[fi['classIdx']]
            if ci is not None and 0 <= ci < len(is_a) and is_a[ci]:
                s['aRf'] += rf; s['aN'] += 1
        elif row[fi['statusIdx']] == resigned_idx:
            s['res'].add(row[fi['employeeIdx']])
    del r
    res_ids = collections.defaultdict(set)
    for (ln, pi), s in g.items():
        res_ids[ln] |= s['res']
    out = {'periods': periods, 'lines': {}, 'resIds': res_ids}
    for ln in ALL_LINES:
        series = []
        for pi, p in enumerate(periods):
            s = g.get((ln, pi))
            if not s or not s['n']:
                series.append(None); continue
            series.append({'cov': s['cov'], 'rf': s['rf'], 'n': s['n'], 'vis': s['vis'], 'tgt': s['tgt'],
                           'aRf': s['aRf'], 'aN': s['aN'], 'hc': len(s['act']), 'res': len(s['res']),
                           'below': s['below'], 'over': s['over']})
        out['lines'][ln] = series
    # validation hook vs the Coverage page's own August team figures
    tc = {K(t['team']): t for t in d['teamComparison']}
    worst = 0
    for ln in ALL_LINES:
        s = out['lines'][ln][-1]
        t = tc.get(K(TEAM_OF.get(ln, ln)))
        if s and t:
            worst = max(worst, abs(s['cov'] / s['n'] - t['coveragePct']))
    # Right Frequency follows js/analytics.js (visits >= prorated target when a
    # prorated target exists), i.e. what the live Coverage page shows; the ETL's
    # precomputed teamComparison can differ by <1 pt on prorated rows, so only
    # Coverage is checked strictly here.
    log(f'execution: {len(periods)} periods; max |coverage diff| vs Coverage page {periods[-1]} team figures = {worst:.4f}')
    if worst > 0.001:
        log('  *** WARNING: coverage differs from the Coverage page -- check the rule mirror')
    return out


# ============================================================ 3. COACHING + FIELD DAYS
def build_managers(months_labels):
    co, _ = load_b64('coaching.data.js')
    months = co['period']['months']
    agg = collections.defaultdict(lambda: [0, 0, 0, 0, 0])
    for m in co['managers']:
        if m.get('title') not in ('District Manager', 'District Sales Manager', 'Senior District Manager'):
            continue
        ln = KEY2LINE.get(K(m.get('line')))
        if not ln:
            continue
        for mo, x in (m.get('monthly') or {}).items():
            if not x or not x.get('activeHalfMonth'):
                continue
            a = agg[(ln, mo)]
            a[0] += x.get('visits') or 0; a[1] += x.get('coachingDays') or 0
            a[2] += x.get('coachedOnRoster') or 0; a[3] += x.get('activeTeamSize') or 0; a[4] += 1
    wd, _ = load_b64('working_days.data.js')
    fd = collections.defaultdict(list)
    wmonths = wd['monthOrder']
    for mname, rows in wd['employees'].get('DM_DSM', {}).items():
        for e in rows:
            ln = KEY2LINE.get(K(e.get('line')))
            if ln and e.get('fieldPct') is not None:
                fd[(ln, mname)].append(e['fieldPct'])
    out = {'coachMonths': months, 'fieldMonths': wmonths, 'lines': {}}
    for ln in ALL_LINES:
        cm = []
        for mo in months:
            a = agg.get((ln, mo))
            cm.append({'vis': a[0], 'days': a[1], 'coached': a[2], 'team': a[3], 'dms': a[4]} if a and a[1] else None)
        fm = []
        for mo in wmonths:
            v = fd.get((ln, mo))
            fm.append({'avg': sum(v) / len(v), 'low': sum(1 for p in v if p < 0.7), 'n': len(v)} if v else None)
        out['lines'][ln] = {'coach': cm, 'field': fm}
    log(f'managers: coaching {months[0]}..{months[-1]}, field days {wmonths[0]}..{wmonths[-1]}')
    return out


# ============================================================ 4. IQVIA
def build_iqvia(mode='YTD'):
    """mode 'YTD' = Jan..latest month vs the same months last year (drives all comments);
    mode 'MAT' = the latest 12 months vs the 12 months before (display toggle only)."""
    flat, raw = load_b64('iqvia.data.js')
    m = re.search(r'"?b64Data"?\s*:\s*"[^"]+"', raw)
    rest = raw[:m.start()] + '"b64Data":""' + raw[m.end():]
    meta = json.loads(rest[rest.index('{'):rest.rindex('}') + 1])
    LK = meta['lookups']
    P = LK['periods']; corps = LK['corps']; prods = LK['prods']; dm1s = LK['dm1s']
    lines = LK['lines']; bus = LK['bus']
    latest = P[-1]; ly, lm = int(latest[:4]), int(latest[5:7])
    if mode == 'MAT':
        mi = lambda p: int(p[:4]) * 12 + int(p[5:7]) - 1
        L = mi(latest)
        cur = {i for i, p in enumerate(P) if L - 11 <= mi(p) <= L}
        prv = {i for i, p in enumerate(P) if L - 23 <= mi(p) <= L - 12}
        if len(cur) < 12 or len(prv) < 12:
            log(f'iqvia MAT: only {len(cur)}/{len(prv)} months available -- MAT skipped')
            return None
    else:
        cur = {i for i, p in enumerate(P) if int(p[:4]) == ly and int(p[5:7]) <= lm}
        prv = {i for i, p in enumerate(P) if int(p[:4]) == ly - 1 and int(p[5:7]) <= lm}
    last_i = len(P) - 1; prev_m = last_i - 1
    zeta = next(i for i, c in enumerate(corps) if 'ZETA PHARM' in c.upper())
    other = dm1s.index('OTHER MARKET') if 'OTHER MARKET' in dm1s else -99
    N = len(flat)
    # --- pass 1: entity (bu / line) markets + corp shares, dm1 markets, product totals
    ent = collections.defaultdict(lambda: [0.0] * 12)   # key -> [zV,tV,zVp,tVp,zS,tS,zSp,tSp, zVm,tVm,zVpm,tVpm(month)]
    corp_ent = collections.defaultdict(lambda: [0.0, 0.0])  # (entkey, corp) -> [cur V, prev V]
    corp_prod_ent = collections.defaultdict(lambda: [0.0, 0.0])  # (entkey, corp, prod) -> [cur V, prev V]
    dm1_tot = collections.defaultdict(lambda: [0.0, 0.0, 0.0, 0.0])  # dm1 -> [V, Vp, S, Sp]
    prod_dm1 = collections.defaultdict(lambda: [0.0, 0.0, 0.0, 0.0])  # (prod, dm1) -> [V,Vp,S,Sp]
    prod_corp = {}
    zeta_prod_line = collections.defaultdict(float)  # (prod, line) -> cur V
    zp_month = collections.defaultdict(float)         # (prod, period) -> V, all DM1s incl. OTHER MARKET
    zp_lines = collections.defaultdict(collections.Counter)
    for i in range(0, N, 14):
        d1 = flat[i + 4]
        if flat[i] == zeta:
            tz = flat[i + 2]
            if tz in cur or tz in prv:
                zp_month[(prods[flat[i + 1]], P[tz])] += flat[i + 6]
                if tz in cur:
                    li_ = flat[i + 8]
                    zp_lines[prods[flat[i + 1]]][lines[li_] if 0 <= li_ < len(lines) else '-'] += flat[i + 6]
        if d1 == other:
            continue
        t = flat[i + 2]
        ic, ip = t in cur, t in prv
        im, ipm = t == last_i, t == prev_m
        if not (ic or ip or im or ipm):
            continue
        c = flat[i]; pr = flat[i + 1]; v = flat[i + 6]; su = flat[i + 7]
        li = flat[i + 8]; bi = flat[i + 9]; z = c == zeta
        keys = []
        if 0 <= bi < len(bus):
            keys.append('BU:' + bus[bi])
            if bus[bi] in BU_LINES:
                keys.append('ALL')   # the 4 promoted BUs (Non-Promoted / Other Markets excluded)
            if 0 <= li < len(lines):
                keys.append('LINE:' + lines[li])
        for k in keys:
            e = ent[k]
            if ic:
                e[1] += v; e[5] += su
                if z: e[0] += v; e[4] += su
                corp_ent[(k, c)][0] += v
                corp_prod_ent[(k, c, pr)][0] += v
            if ip:
                e[3] += v; e[7] += su
                if z: e[2] += v; e[6] += su
                corp_ent[(k, c)][1] += v
                corp_prod_ent[(k, c, pr)][1] += v
            if im:
                e[9] += v
                if z: e[8] += v
            if ipm:
                e[11] += v
                if z: e[10] += v
        if ic or ip:
            dt = dm1_tot[d1]; pd = prod_dm1[(pr, d1)]
            if ic:
                dt[0] += v; dt[2] += su; pd[0] += v; pd[2] += su
                if z and 0 <= li < len(lines):
                    zeta_prod_line[(pr, lines[li])] += v
            else:
                dt[1] += v; dt[3] += su; pd[1] += v; pd[3] += su
            prod_corp[pr] = c
    del flat
    # --- products of each company inside each entity market
    cprods = collections.defaultdict(list)   # (k, corp) -> [(prod, V, Vp)]
    for (k, c, pr), v in corp_prod_ent.items():
        cprods[(k, c)].append((pr, v[0], v[1]))
    del corp_prod_ent

    def prod_list(k, c, e, n=3, by='value'):
        """Top products of company c in entity k. by='value' -> largest YTD value;
        by='gain'/'loss' -> largest share-point change (each product's share of the
        entity market now minus last period)."""
        rows = []
        for pr, v, vp in cprods.get((k, c), []):
            s = div(v, e[1]) or 0; sp = div(vp, e[3]) or 0
            rows.append({'prod': prods[pr], 'share': s, 'shareP': sp, 'dShare': s - sp,
                         'growth': (v / vp - 1) if vp else None, 'v': v})
        if by == 'gain':
            rows = [r for r in rows if r['dShare'] > 0]; rows.sort(key=lambda r: -r['dShare'])
        elif by == 'loss':
            rows = [r for r in rows if r['dShare'] < 0]; rows.sort(key=lambda r: r['dShare'])
        else:
            rows = [r for r in rows if r['v'] > 0]; rows.sort(key=lambda r: -r['v'])
        return [{kk: r[kk] for kk in ('prod', 'share', 'shareP', 'dShare', 'growth')} for r in rows[:n]]

    # --- entity summaries
    def ent_summary(k):
        e = ent.get(k)
        if not e or not e[1]:
            return None
        cs = [(c, v[0], v[1]) for (kk, c), v in corp_ent.items() if kk == k]
        cs.sort(key=lambda x: -x[1])
        csp = sorted(cs, key=lambda x: -x[2])
        rank_now = next((i + 1 for i, x in enumerate(cs) if x[0] == zeta), None)
        rank_prev = next((i + 1 for i, x in enumerate(csp) if x[0] == zeta), None)
        top = []
        for c, v, vp in cs[:8]:
            top.append({'corp': corps[c], 'zeta': c == zeta, 'share': div(v, e[1]), 'shareP': div(vp, e[3]),
                        'growth': (v / vp - 1) if vp else None, 'prods': prod_list(k, c, e, 3, 'value')})
        movers = []
        for c, v, vp in cs:
            s = div(v, e[1]) or 0
            if s < TH['minShare'] or not vp:
                continue
            movers.append({'corp': corps[c], 'zeta': c == zeta, 'share': s, 'dShare': s - (div(vp, e[3]) or 0), 'growth': v / vp - 1, '_c': c})
        movers.sort(key=lambda x: -x['dShare'])
        gainers, losers = movers[:3], movers[::-1][:3]
        for m_ in gainers:
            m_['prods'] = prod_list(k, m_['_c'], e, 2, 'gain')
        for m_ in losers:
            m_['prods'] = prod_list(k, m_['_c'], e, 2, 'loss')
        for m_ in movers:
            m_.pop('_c', None)
        return {
            'shareSU': div(e[4], e[5]), 'shareSUp': div(e[6], e[7]),
            'shareV': div(e[0], e[1]), 'shareVp': div(e[2], e[3]),
            'mktV': e[1], 'mktVp': e[3], 'zV': e[0], 'zVp': e[2],
            'mktG': (e[1] / e[3] - 1) if e[3] else None, 'zG': (e[0] / e[2] - 1) if e[2] else None,
            'evi': round(100 * (e[4] / e[6]) / (e[5] / e[7])) if e[6] and e[7] else None,   # SU basis, as getBlendedBuShare
            'eviV': round(100 * (e[0] / e[2]) / (e[1] / e[3])) if e[2] and e[3] else None,
            'shareVm': div(e[8], e[9]), 'shareVpm': div(e[10], e[11]),
            'rank': rank_now, 'rankP': rank_prev, 'nCorps': len(cs),
            'topCorps': top, 'gainers': gainers, 'losers': losers,
        }
    ents = {'ALL': ent_summary('ALL')}
    for b in BU_LINES:
        ents['BU:' + b] = ent_summary('BU:' + b)
    for ln in ALL_LINES:
        iql = IQ_LINE_OF.get(ln, ln)
        ents['LINE:' + ln] = ent_summary('LINE:' + iql)
    # --- brand (Zeta product) analysis in its main DM1 market
    zeta_prods = collections.defaultdict(float)
    for (pr, d1), v in prod_dm1.items():
        if prod_corp.get(pr) == zeta:
            zeta_prods[pr] += v[0]
    by_dm1 = collections.defaultdict(list)
    for (pr, d1), v in prod_dm1.items():
        by_dm1[d1].append((pr, v))
    brands = {}
    for pr, vtot in zeta_prods.items():
        if vtot <= 0:
            continue
        # main dm1 by current value
        cands = [(d1, v) for (p, d1), v in prod_dm1.items() if p == pr]
        d1, v = max(cands, key=lambda x: x[1][0])
        mt = dm1_tot[d1]
        if not mt[0]:
            continue
        # line of this product (Zeta rows' line tag, by value)
        pl = [(l, x) for (p, l), x in zeta_prod_line.items() if p == pr]
        pline = max(pl, key=lambda x: x[1])[0] if pl else None
        comp = []
        for p2, v2 in by_dm1[d1]:
            s = div(v2[0], mt[0]) or 0
            sp = div(v2[1], mt[1]) or 0
            comp.append({'prod': prods[p2], 'corp': corps[prod_corp.get(p2, 0)], 'zeta': prod_corp.get(p2) == zeta,
                         'share': s, 'shareP': sp, 'growth': (v2[0] / v2[1] - 1) if v2[1] else None, 'v': v2[0]})
        comp.sort(key=lambda x: -x['v'])
        rank = next((i + 1 for i, x in enumerate(comp) if x['prod'] == prods[pr]), None)
        prank_list = sorted(comp, key=lambda x: -x['shareP'])
        rankP = next((i + 1 for i, x in enumerate(prank_list) if x['prod'] == prods[pr] and x['shareP'] > 0), None)
        elig = [x for x in comp if x['share'] >= TH['minShare'] and x['shareP'] > 0 and not x['prod'] == prods[pr]]
        gain = max(elig, key=lambda x: x['share'] - x['shareP'], default=None)
        lose = min(elig, key=lambda x: x['share'] - x['shareP'], default=None)
        me = next(x for x in comp if x['prod'] == prods[pr])
        # New entrants: competitor products with no sales in the prior-year YTD
        # and >= 0.5% value share now (the growth-ranking eligibility threshold).
        new_ent = [{k: x[k] for k in ('prod', 'corp', 'share')} for x in comp
                   if not x['zeta'] and x['shareP'] == 0 and x['share'] >= TH['minShare']]
        brands[prods[pr]] = {
            'line': pline, 'dm1': dm1s[d1], 'mktV': mt[0], 'mktG': (mt[0] / mt[1] - 1) if mt[1] else None,
            'v': v[0], 'vP': v[1], 'growth': (v[0] / v[1] - 1) if v[1] else None,
            'share': me['share'], 'shareP': me['shareP'],
            'shareSU': div(v[2], mt[2]), 'shareSUp': div(v[3], mt[3]),
            'evi': round(100 * (v[0] / v[1]) / (mt[0] / mt[1])) if v[1] and mt[1] else None,
            'rank': rank, 'rankP': rankP, 'nProds': len(comp),
            'competitors': [{k: x[k] for k in ('prod', 'corp', 'zeta', 'share', 'shareP', 'growth')} for x in comp if x['prod'] != prods[pr]][:5],
            'topGainer': {k: gain[k] for k in ('prod', 'corp', 'share', 'shareP', 'growth')} if gain else None,
            'topLoser': {k: lose[k] for k in ('prod', 'corp', 'share', 'shareP', 'growth')} if lose else None,
            'newEntrants': new_ent,
        }
    log(f'iqvia {mode}: period {latest} ({len(cur)} months vs the {len(prv)} before), {len(brands)} Zeta brands with a DM1 market')
    for b in BU_LINES:
        e = ents['BU:' + b]
        if e:
            log(f'  {b}: SU share {100*e["shareSU"]:.2f}% (PY {100*(e["shareSUp"] or 0):.2f}%), value share {100*e["shareV"]:.2f}%, EVI SU {e["evi"]} / value {e["eviV"]}')
    zpm = collections.defaultdict(dict)
    for (pn, per), v in zp_month.items():
        zpm[pn][per] = v
    return {'mode': mode, 'period': latest, 'ytdMonths': len(cur), 'entities': ents, 'brands': brands,
            'zetaProdMonthly': dict(zpm), 'zetaProdLines': {k: dict(v) for k, v in zp_lines.items()},
            'curPeriods': sorted(P[i] for i in cur), 'prevPeriods': sorted(P[i] for i in prv)}


# ============================================================ 4b. FULL-YEAR TARGETS
def build_fy_targets():
    """Full-year Official targets that exist in the source files. Today only the
    CHC BU has one: CHC_BU_YTD_PERFROMANCE.xlsx sheet 'New CHC Target' (annual
    value + CHC_SALES % of CHC + monthly phasing). Other lines have no Sep-Dec
    target loaded anywhere, so they get none -- nothing is extrapolated."""
    out = {}
    path = os.path.join(ROOT, 'ZETA SALES_2026', 'CHC_BU_YTD_PERFROMANCE.xlsx')
    try:
        from python_calamine import CalamineWorkbook
        rows = CalamineWorkbook.from_path(path).get_sheet_by_name('New CHC Target').to_python()
    except Exception as e:
        log(f'FY targets: New CHC Target sheet not read ({e}) -- no full-year targets')
        return out
    annual = pct_sales = None; phasing = None
    for r in rows:
        lab = str(r[0]).strip() if r and r[0] is not None else ''
        vals = [v for v in r[1:] if isinstance(v, (int, float))]
        if lab.startswith('Annual Target Value') and vals:
            annual = float(vals[0])
        elif lab.startswith('CHC_SALES target as %') and vals:
            pct_sales = float(vals[0])
        elif lab == 'Phasing %' and len(vals) >= 12:
            phasing = [float(v) for v in vals[:12]]
    if annual:
        out['CHC'] = {'fy': annual, 'phasing': phasing, 'source': 'CHC_BU_YTD_PERFROMANCE.xlsx / New CHC Target'}
        if pct_sales:
            out['CHC_SALES'] = {'fy': annual * pct_sales, 'phasing': phasing, 'source': 'CHC_BU_YTD_PERFROMANCE.xlsx / New CHC Target (CHC_SALES = %.0f%% of CHC)' % (100 * pct_sales)}
    log('FY targets: ' + (', '.join(f'{k} {v["fy"]/1e6:.1f}M' for k, v in out.items()) or 'none'))
    return out


def landing(E, lines, kind, fy_targets, sales_months):
    """Run-rate projection (arithmetic, not a forecast): YTD actual + the
    average of the last 3 months x remaining months. Required monthly sales to
    reach the full-year target only where one exists."""
    mA = E['sales']['mA']; n = len(mA); rem = 12 - n
    pace = sum(mA[-3:]) / min(3, n)
    ytdA = sum(mA); ytdO = sum(E['sales']['mO'])
    res = {'pace': pace, 'paceMonths': sales_months[-3:], 'remMonths': rem, 'landing': ytdA + pace * rem,
           'fy': None, 'required': None, 'fySource': None}
    key = lines[0] if kind == 'line' else ('CHC' if kind == 'bu' and lines[0] == 'CHC' else None)
    t = fy_targets.get(key) if key else None
    if t:
        res['fy'] = t['fy']; res['fySource'] = t['source']
        res['required'] = (t['fy'] - ytdA) / rem if rem else None
    return res


# ============================================================ 4c. SELL-IN vs IQVIA (brand map)
MAP_HEADERS = ['IQVIA product', 'Sales brand', 'Status', 'Basis', 'IQVIA YTD value (EGP)', 'IQVIA lines', 'Sales brand lines']
IQ2SALES_LINE = {'CNS': 'NEUROSCIENCE'}


def _norm(x):
    return re.sub(r'[^A-Z0-9]', '', str(x or '').upper())


def build_brand_map(sales, iq):
    """Links sales brands to IQVIA Zeta products through Business Review/Brand_IQVIA_Map.xlsx.
    If the file does not exist a DRAFT is written: 'Auto' = the sales brand name is the
    start of the IQVIA product name AND the product sells in one of the brand's lines;
    every other candidate is 'Review' and is NOT used until Ahmed sets it to 'Confirmed'.
    The file is never overwritten once it exists."""
    try:
        import openpyxl
    except ImportError:
        log('brand map: openpyxl not installed -- sell-in vs IQVIA skipped')
        return {'groups': [], 'review': 0, 'unmapped': 0, 'file': None}
    brands = sales['brandLines']
    if not os.path.exists(MAP_XLSX):
        os.makedirs(BR_DIR, exist_ok=True)
        rows = []
        bn = {b: _norm(b) for b in brands}
        for prod, lines_v in sorted(iq['zetaProdLines'].items(), key=lambda kv: -sum(kv[1].values())):
            tot = sum(lines_v.values())
            pl = [IQ2SALES_LINE.get(l, l) for l, _ in sorted(lines_v.items(), key=lambda kv: -kv[1])]
            pn = _norm(prod)
            cands = [b for b in brands if pn.startswith(bn[b])]
            if cands:
                b = max(cands, key=lambda x: len(bn[x]))
                ok = bool(set(pl) & set(brands[b]))
                rows.append([prod, b, 'Auto' if ok else 'Review', 'name match' if ok else 'name match, but IQVIA line differs from the sales lines', round(tot), ', '.join(pl), ', '.join(brands[b])])
                continue
            rev = [b for b in brands if bn[b].startswith(pn)]
            if rev:
                for b in rev:
                    rows.append([prod, b, 'Review', 'IQVIA name is a shortened form of the sales brand', round(tot), ', '.join(pl), ', '.join(brands[b])])
                continue
            close = difflib.get_close_matches(prod.upper(), list(brands), n=1, cutoff=0.75)
            if close:
                b = close[0]
                rows.append([prod, b, 'Review', 'similar spelling', round(tot), ', '.join(pl), ', '.join(brands[b])])
            else:
                rows.append([prod, '', 'No sales brand', 'no sales brand with a similar name', round(tot), ', '.join(pl), ''])
        wb = openpyxl.Workbook(); ws = wb.active; ws.title = 'Map'
        ws.append(MAP_HEADERS)
        for r in rows:
            ws.append(r)
        for col, w in zip('ABCDEFG', (26, 24, 16, 48, 20, 28, 28)):
            ws.column_dimensions[col].width = w
        ws2 = wb.create_sheet('How to use')
        for line in ['Brand_IQVIA_Map -- links sales brands to IQVIA Zeta products for the BU Business Review page.',
                     'Status: Auto = used (name match + same line). Confirmed = used (set by you). Review = NOT used until you change it to Confirmed.',
                     'Excluded = never used. No sales brand = IQVIA product without a matching sales brand (informational).',
                     'One IQVIA product can link to several sales brands and vice versa (one row per pair). Add rows freely.',
                     'The refresh never overwrites this file. Delete it only if you want a fresh draft.']:
            ws2.append([line])
        wb.save(MAP_XLSX)
        log(f'brand map: DRAFT written to {MAP_XLSX} ({sum(1 for r in rows if r[2]=="Auto")} Auto, {sum(1 for r in rows if r[2]=="Review")} Review)')
    wb = openpyxl.load_workbook(MAP_XLSX, read_only=True, data_only=True)
    ws = wb['Map'] if 'Map' in wb.sheetnames else wb.worksheets[0]
    it = ws.iter_rows(values_only=True); hdr = [str(h or '').strip() for h in next(it)]
    ix = {h: i for i, h in enumerate(hdr)}
    pairs = []; review = []; unmapped = 0
    for r in it:
        if not r or r[ix['IQVIA product']] is None:
            continue
        prod = str(r[ix['IQVIA product']]).strip(); b = str(r[ix['Sales brand']] or '').strip(); stt = str(r[ix['Status']] or '').strip().title()
        if stt in ('Auto', 'Confirmed') and b:
            pairs.append((b, prod))
        elif stt == 'Review':
            review.append({'prod': prod, 'brand': b, 'basis': str(r[ix['Basis']] or '')})
        elif stt == 'No Sales Brand':
            unmapped += 1
    # connected components -> groups
    parent = {}
    def f(x):
        parent.setdefault(x, x)
        while parent[x] != x:
            parent[x] = parent[parent[x]]; x = parent[x]
        return x
    for b, p in pairs:
        parent[f(('S', b))] = f(('I', p))
    comp = collections.defaultdict(lambda: {'sales': set(), 'iqvia': set()})
    for b, p in pairs:
        c = comp[f(('S', b))]; c['sales'].add(b); c['iqvia'].add(p)
    groups = [{'sales': sorted(c['sales']), 'iqvia': sorted(c['iqvia'])} for c in comp.values()]
    log(f'brand map: {len(pairs)} links used -> {len(groups)} brand groups; {len(review)} rows to review; {unmapped} IQVIA products without a sales brand')
    return {'groups': groups, 'review': review, 'unmapped': unmapped, 'file': os.path.relpath(MAP_XLSX, ROOT)}


def sellout_groups(bmap, sales, iq):
    months = sales['months']; n = len(months)
    py = {m: str(int(m[:4]) - 1) + m[4:] for m in months}
    out = []
    for g in bmap['groups']:
        si = [sum(sales['brandMonthly'].get(b, [0] * n)[i] for b in g['sales']) for i in range(n)]
        im = [sum(iq['zetaProdMonthly'].get(p, {}).get(m, 0) for p in g['iqvia']) for m in months]
        imPY = sum(iq['zetaProdMonthly'].get(p, {}).get(py[m], 0) for p in g['iqvia'] for m in months)
        base_n = n - 2
        siB, siR = sum(si[:base_n]) / base_n, sum(si[base_n:]) / 2
        imB, imR = sum(im[:base_n]) / base_n, sum(im[base_n:]) / 2
        lines_ = sorted({l for b in g['sales'] for l in sales['brandLines'].get(b, [])})
        out.append({'name': ' + '.join(g['sales']), 'sales': g['sales'], 'iqvia': g['iqvia'], 'lines': lines_,
                    'si': [round(v) for v in si], 'im': [round(v) for v in im],
                    'ytdSi': round(sum(si)), 'ytdIm': round(sum(im)), 'imYoY': (sum(im) / imPY - 1) if imPY else None,
                    'siChg': (siR / siB - 1) if siB else None, 'imChg': (imR / imB - 1) if imB else None,
                    'siBase': siB, 'siRecent': siR, 'imBase': imB, 'smallBase': siB < 250e3 or imB < 250e3, 'baseMonths': [months[0], months[base_n - 1]], 'recentMonths': months[base_n:]})
    out.sort(key=lambda r: -r['ytdSi'])
    return out


# ============================================================ 4d. CUSTOMER BASE
CUST_LINE = {'NEUROSCIENCE': 'CNS'}


def build_customers():
    """Pharmacy customer base per scope from cache/customer_analytics.data.js (Chain
    Pharmacy + Retail). Segments are the Customer Health definitions: New = bought in
    the latest month only; Retained = latest and previous month; Reactivated = latest
    month, not previous, but earlier; Lost = previous month, not latest; Inactive = neither."""
    try:
        d, _ = load_b64('customer_analytics.data.js')
    except Exception as e:
        log(f'customers: not read ({e})'); return {}, None
    SEG = ('New', 'Retained', 'Reactivated', 'Lost', 'Inactive')
    Z = lambda: {'n': collections.Counter(), 'v': collections.Counter(), 'freq': 0}
    agg = collections.defaultdict(Z)
    months = None
    for cname, cl in d['clusters'].items():
        months = cl.get('months') or months
        for cu in cl['customers']:
            a = agg['ALL']; seg = cu.get('bridgeSegment'); a['n'][seg] += 1; a['v'][seg] += cu.get('value') or 0
            if cu.get('frequencySegment') == 'Frequent': a['freq'] += 1
            for bu, x in (cu.get('byBU') or {}).items():
                a = agg['BU:' + bu]; seg = x.get('bridgeSegment'); a['n'][seg] += 1; a['v'][seg] += x.get('value') or 0
                if x.get('frequencySegment') == 'Frequent': a['freq'] += 1
                for ln, y in (x.get('byLine') or {}).items():
                    a = agg['LINE:' + ln]; seg = y.get('bridgeSegment'); a['n'][seg] += 1; a['v'][seg] += y.get('value') or 0
                    if y.get('frequencySegment') == 'Frequent': a['freq'] += 1
    out = {}
    for k, a in agg.items():
        out[k] = {'counts': {s: a['n'].get(s, 0) for s in SEG}, 'values': {s: round(a['v'].get(s, 0)) for s in SEG},
                  'total': sum(a['n'].values()), 'frequent': a['freq']}
    log(f'customers: {out.get("ALL", {}).get("total", 0)} pharmacies, months {months[0] if months else "?"}..{months[-1] if months else "?"}')
    return out, months


def customers_for(key, kind, lines, cust):
    if kind == 'line' or key == 'BU:CHC':   # dashboard rule: CHC BU = CHC line
        return cust.get('LINE:' + CUST_LINE.get(lines[0], lines[0]))
    return cust.get(key)


# ============================================================ 4e. ACTION TRACKER
ACT_HEADERS = ['ID', 'Scope', 'Review month', 'Action / question', 'Owner', 'Due date', 'Status', 'Update / comment', 'Created on', 'Source']


def owners_map():
    s = open(os.path.join(CACHE, 'teamkpis.data.js'), encoding='utf-8').read()
    j = json.loads(s[s.index('{'):s.rindex('}') + 1])
    line_owner = {}; bu_owner = {}
    for team, nsm in j.get('teamToNsm', {}).items():
        ln = KEY2LINE.get(K(team))
        if ln:
            line_owner[ln] = nsm
    for team, head in j.get('teamToBu', {}).items():
        ln = KEY2LINE.get(K(team))
        if ln:
            bu_owner[LINE_BU[ln]] = head
    return line_owner, bu_owner


def build_actions(entities, review_month):
    """Business Review/BU_Review_Actions.xlsx. Created once (pre-filled with the current
    questions, Status Open, owner = BU head / NSM); after that it is only READ -- Ahmed
    edits owners, due dates, status and updates in Excel."""
    try:
        import openpyxl
    except ImportError:
        log('actions: openpyxl not installed -- action tracker skipped'); return [], None
    if not os.path.exists(ACTIONS_XLSX):
        os.makedirs(BR_DIR, exist_ok=True)
        try:
            lo, bo = owners_map()
        except Exception:
            lo, bo = {}, {}
        wb = openpyxl.Workbook(); ws = wb.active; ws.title = 'Actions'; ws.append(ACT_HEADERS)
        n = 0; today = datetime.date.today().isoformat()
        for k, e in entities.items():
            if e['kind'] == 'all':
                continue
            owner = bo.get(e['bu']) if e['kind'] == 'bu' else lo.get(e['lines'][0], '')
            for q in e['comments']['questions']:
                n += 1
                ws.append([f'A{n:03d}', e['name'], review_month, q, owner or '', None, 'Open', '', today, 'Auto (page question)'])
        for col, w in zip('ABCDEFGHIJ', (7, 16, 13, 70, 30, 12, 12, 40, 12, 18)):
            ws.column_dimensions[col].width = w
        ws2 = wb.create_sheet('How to use')
        for line in ['BU_Review_Actions -- follow-up of the BU Business Review questions.',
                     'Scope must match the page names: "CHC BU", "Cluster BU", "DIAB BU", "GIT BU" or a line name (e.g. ORTHO-I).',
                     'Status: Open / In progress / Done. Due date as a date. The page flags Open or In progress items past their due date as overdue.',
                     'Add new rows for new actions (any ID). The refresh never overwrites this file.']:
            ws2.append([line])
        wb.save(ACTIONS_XLSX)
        log(f'actions: tracker created with {n} open questions -> {ACTIONS_XLSX}')
    wb = openpyxl.load_workbook(ACTIONS_XLSX, read_only=True, data_only=True)
    ws = wb['Actions'] if 'Actions' in wb.sheetnames else wb.worksheets[0]
    it = ws.iter_rows(values_only=True); hdr = [str(h or '').strip() for h in next(it)]
    ix = {h: i for i, h in enumerate(hdr)}
    today = datetime.date.today(); acts = []
    for r in it:
        if not r or not r[ix['Action / question']]:
            continue
        due = r[ix['Due date']]
        if isinstance(due, datetime.datetime):
            due = due.date()
        elif isinstance(due, str) and due.strip():
            try:
                due = datetime.date.fromisoformat(due.strip()[:10])
            except ValueError:
                due = None
        elif not isinstance(due, datetime.date):
            due = None
        st = str(r[ix['Status']] or 'Open').strip()
        done = st.lower() in ('done', 'closed', 'complete', 'completed')
        acts.append({'id': str(r[ix['ID']] or ''), 'scope': str(r[ix['Scope']] or '').strip(), 'month': str(r[ix['Review month']] or ''),
                     'action': str(r[ix['Action / question']]).strip(), 'owner': str(r[ix['Owner']] or ''), 'due': due.isoformat() if due else None,
                     'status': st, 'done': done, 'overdue': bool(due and due < today and not done), 'update': str(r[ix['Update / comment']] or '')})
    log(f'actions: {len(acts)} rows read ({sum(a["done"] for a in acts)} done, {sum(a["overdue"] for a in acts)} overdue)')
    return acts, os.path.relpath(ACTIONS_XLSX, ROOT)


# ============================================================ 4f. DATA GAPS
def data_gaps(E, kind, ls, sales, exe_periods, iq_e, bmap, mapped_sales, entity_actions, sales_months):
    """What this page cannot show for the scope, and why. Facts about missing inputs only."""
    g = []
    if not (E.get('landing') or {}).get('fy'):
        g.append({'area': 'Targets', 'text': 'Full-year (Sep–Dec) target not loaded for this scope: no full-year landing or required run-rate. Only CHC and CHC_SALES have one (New CHC Target sheet).'})
    g.append({'area': 'Sales', 'text': '2025 own sales not loaded: no growth vs last year on sell-in (IQVIA growth is shown instead).'})
    oth = [sales_months[i] for i, v in enumerate(E['sales']['mOther']) if abs(v) >= 1]
    if oth:
        g.append({'area': 'Sales', 'text': 'Volume/price split not possible for ' + ', '.join(MON[int(m[5:])] for m in oth) + ': the target has value but no units in those months (shown as "other").'})
    if exe_periods and exe_periods[0] != 'January':
        g.append({'area': 'Execution', 'text': f'Coverage, Right Frequency, coaching and field days start in {exe_periods[0]} (earlier months not loaded).'})
    if not iq_e:
        g.append({'area': 'IQVIA', 'text': 'No IQVIA market rows tagged to this scope.'})
    scope_lines = set(ls)
    rev = [r for r in bmap['review'] if kind == 'all' or scope_lines & set(sales['brandLines'].get(r['brand'], []))]
    if rev:
        g.append({'area': 'Brand map', 'text': f'{len(rev)} sales brand ↔ IQVIA product link(s) waiting for review, not used: ' + '; '.join(f'{r["prod"]} → {r["brand"]}' for r in rev) + '.'})
    um = sorted(b for b, bl in sales['brandLines'].items() if b not in mapped_sales and (kind == 'all' or scope_lines & set(bl)))
    if um:
        g.append({'area': 'Brand map', 'text': 'Sales brands with no IQVIA product linked (no sell-in vs in-market): ' + ', '.join(um) + '.'})
    if entity_actions:
        no_own = sum(1 for a in entity_actions if not a['owner'] and not a['done'])
        no_due = sum(1 for a in entity_actions if not a['due'] and not a['done'])
        if no_own or no_due:
            g.append({'area': 'Actions', 'text': f'Open actions without an owner: {no_own}; without a due date: {no_due}.'})
    return g


# ============================================================ 5. ENTITY ROLL-UP
def roll(lines, sales, exe, mgr):
    months = sales['months']
    tot = collections.defaultdict(lambda: [0.0] * len(months))
    for ln in lines:
        if len(lines) > 1 and ln in NOT_IN_BU_TOTAL:
            continue
        s = sales['lines'][ln]
        for k in ('mA', 'mO', 'mS', 'mW', 'mVol', 'mPrice', 'mOther'):
            for i, v in enumerate(s[k]):
                tot[k][i] += v
    periods = exe['periods']
    ex = []
    for pi in range(len(periods)):
        acc = collections.Counter()
        for ln in lines:
            s = exe['lines'][ln][pi]
            if s:
                acc.update({k: v for k, v in s.items()})
        ex.append(dict(acc) if acc.get('n') else None)
    cm = []
    for i in range(len(mgr['coachMonths'])):
        acc = collections.Counter()
        for ln in lines:
            x = mgr['lines'][ln]['coach'][i]
            if x:
                acc.update(x)
        cm.append(dict(acc) if acc.get('days') else None)
    fm = []
    for i in range(len(mgr['fieldMonths'])):
        tw = 0; n = 0; low = 0
        for ln in lines:
            x = mgr['lines'][ln]['field'][i]
            if x:
                tw += x['avg'] * x['n']; n += x['n']; low += x['low']
        fm.append({'avg': tw / n, 'low': low, 'n': n} if n else None)
    res = set()
    for ln in lines:
        res |= exe['resIds'].get(ln, set())
    return {'sales': {k: [round(v) for v in tot[k]] for k in ('mA', 'mO', 'mS', 'mW', 'mVol', 'mPrice', 'mOther')}, 'exec': ex, 'coach': cm, 'field': fm, 'resignedYtd': len(res)}


# ============================================================ 6. COMMENTS (rules)
MON = ['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']


def pct(x, d=0):
    return 'n/a' if x is None else f'{100*x:.{d}f}%'


def pts(x, d=1):
    return 'n/a' if x is None else f'{100*x:+.{d}f} pts'


def comments(name, kind, E, sales_months, exe_periods, coach_months, field_months, iq, brands_iq, brands_sales, lines):
    """Returns {headline, strengths[], concerns[], market[], questions[]}. Every
    item is {text, tag:'FACT', conf, impact}: Ahmed 2026-09-26 "don't make any
    hypothesis" -- only statements read or computed directly from the data.
    impact = EGP at stake where one can be computed (used to rank, biggest first)."""
    S = E['sales']; mA, mO, mS = S['mA'], S['mO'], S['mS']
    ytdA, ytdO, ytdS = sum(mA), sum(mO), sum(mS)
    ach = 100 * ytdA / ytdO if ytdO else None
    lastAch = 100 * mA[-1] / mO[-1] if mO[-1] else None
    h1A, h1O = sum(mA[:6]), sum(mO[:6])
    recA, recO = sum(mA[6:]), sum(mO[6:])
    h1Ach = 100 * h1A / h1O if h1O else None
    recAch = 100 * recA / recO if recO else None
    months_below = sum(1 for a, o in zip(mA, mO) if o and a / o < 0.9)
    ex = [x for x in E['exec'] if x]
    exL = E['exec'][-1]
    cov = exL['cov'] / exL['n'] if exL else None
    rf = exL['rf'] / exL['n'] if exL else None
    ytdCov = sum(x['cov'] for x in ex) / sum(x['n'] for x in ex) if ex else None
    ytdRf = sum(x['rf'] for x in ex) / sum(x['n'] for x in ex) if ex else None
    firstCov = ex[0]['cov'] / ex[0]['n'] if ex else None
    firstRf = ex[0]['rf'] / ex[0]['n'] if ex else None
    aRf = exL['aRf'] / exL['aN'] if exL and exL.get('aN') else None
    visit = exL['vis'] / exL['tgt'] if exL and exL['tgt'] else None
    cl = next((x for x in reversed(E['coach']) if x), None)
    cpd = cl['vis'] / cl['days'] if cl else None
    coached = cl['coached'] / cl['team'] if cl and cl['team'] else None
    fl = E['field'][-1]
    supply = (ytdO - ytdS) / ytdO if ytdO and ytdS and ytdO > ytdS else 0
    cpd_t = TH['cpdChcSales'] if lines == ['CHC_SALES'] else TH['cpd']
    hc = exL['hc'] if exL else None
    res_ytd = E.get('resignedYtd', 0)

    st, co, mk, qs = [], [], [], []
    F = lambda t, imp=None: {'text': t, 'tag': 'FACT', 'conf': 90, 'impact': round(abs(imp)) if imp is not None else None}

    # ---- sales
    if ach is not None:
        line = f'YTD sales {ytdA/1e6:.1f}M vs Official target {ytdO/1e6:.1f}M = {ach:.0f}% ({"above" if ach >= 100 else "below"} target by {abs(ytdA-ytdO)/1e6:.1f}M).'
        ytd_item = F(line, ytdA - ytdO)
        (st if ach >= 100 else co).append(ytd_item)
    if h1Ach is not None and recAch is not None:
        if recAch - h1Ach >= 10:
            st.append(F(f'Momentum improving: Jul–Aug achievement {recAch:.0f}% vs Jan–Jun {h1Ach:.0f}%.', recA - recO))
        elif h1Ach - recAch >= 10:
            co.append(F(f'Momentum slowing: Jul–Aug achievement {recAch:.0f}% vs Jan–Jun {h1Ach:.0f}%.', recA - recO))
    if months_below >= 5:
        co.append(F(f'Below 90% of target in {months_below} of {len(mA)} months.'))
        qs.append('What was the target built on (run-rate, market growth, launch curve), and is it still realistic for Sep–Dec?')
    if supply > 0.03:
        co.append(F(f'Stock shortage explains {pct(supply)} of YTD target (Shortage target {ytdS/1e6:.1f}M vs Official {ytdO/1e6:.1f}M).', ytdO - ytdS))
        qs.append('Which SKUs are still short, what is the confirmed recovery date, and how are priority customers being protected?')
    # ---- brand concentration and weak brands (sales cache)
    bs = []
    for ln in lines:
        if len(lines) > 1 and ln in NOT_IN_BU_TOTAL:
            continue
        bs += brands_sales.get(ln, [])
    tA = sum(b['ytdA'] for b in bs)
    if bs and tA > 0:
        top = max(bs, key=lambda b: b['ytdA'])
        sh = top['ytdA'] / tA
        if sh >= 0.5 and len(bs) > 1:
            co.append(F(f'Concentration risk: {top["brand"]} is {pct(sh)} of YTD sales.'))
            qs.append(f'What is the plan if {top["brand"]} slows down, and which brand is ready to take a bigger share?')
        weak = [b for b in bs if b['ytdO'] > 0.05 * sum(x['ytdO'] for x in bs) and b['ytdA'] / b['ytdO'] < 0.8]
        weak.sort(key=lambda b: b['ytdA'] - b['ytdO'])
        if weak:
            co.append(F('Brands below 80% YTD (≥5% of target): ' + ', '.join(f'{b["brand"]} {100*b["ytdA"]/b["ytdO"]:.0f}% ({(b["ytdA"]-b["ytdO"])/1e6:+.1f}M)' for b in weak[:4]) + '.', sum(b['ytdA'] - b['ytdO'] for b in weak[:4])))
            qs.append(f'What is the recovery plan for {weak[0]["brand"]} ({(weak[0]["ytdA"]-weak[0]["ytdO"])/1e6:+.1f}M YTD gap), with monthly milestones?')
        strong = [b for b in bs if b['ytdO'] > 0.05 * sum(x['ytdO'] for x in bs) and b['ytdA'] / b['ytdO'] >= 1.1]
        strong.sort(key=lambda b: -(b['ytdA'] - b['ytdO']))
        if strong:
            st.append(F('Brands above 110% YTD: ' + ', '.join(f'{b["brand"]} {100*b["ytdA"]/b["ytdO"]:.0f}% ({(b["ytdA"]-b["ytdO"])/1e6:+.1f}M)' for b in strong[:4]) + '.', sum(b['ytdA'] - b['ytdO'] for b in strong[:4])))

    # ---- execution
    if cov is not None:
        good = cov >= TH['cov'] and rf > TH['rf']
        msg = f'{exe_periods[-1]} execution: Coverage {pct(cov,1)}, Right Frequency {pct(rf,1)} (bar ≥90% / >80%); YTD {pct(ytdCov,1)} / {pct(ytdRf,1)}.'
        (st if good else co).append(F(msg))
        if firstCov is not None and cov - firstCov >= 0.05:
            st.append(F(f'Coverage up {100*(cov-firstCov):.0f} pts since {exe_periods[0]} ({pct(firstCov)} → {pct(cov)}).'))
        if firstRf is not None and rf - firstRf >= 0.05:
            st.append(F(f'Right Frequency up {100*(rf-firstRf):.0f} pts since {exe_periods[0]} ({pct(firstRf)} → {pct(rf)}).'))
        if aRf is not None and aRf < rf - 0.03:
            co.append(F(f'A-class customers get less frequency than average: A-class RF {pct(aRf)} vs {pct(rf)} overall.'))
            qs.append('Why do A-class customers get lower frequency than B/C, and when will the call plans be re-balanced?')
        if not good:
            qs.append('Which territories drive the gap to Coverage 90% / Right Frequency 80%, and what is the weekly recovery plan?')
    if visit is not None and visit < TH['visit']:
        co.append(F(f'Visit achievement {pct(visit,1)} of planned visits in {exe_periods[-1]}.'))
    # ---- managers
    if cpd is not None:
        if cpd < cpd_t - 0.5:
            co.append(F(f'Coaching intensity {cpd:.1f} calls per coaching day vs target {cpd_t:.0f}; {pct(coached)} of reps coached.'))
            qs.append('How will DMs raise double-visit intensity to target, and who is not coaching every rep monthly?')
        elif coached is not None and coached >= 0.95:
            st.append(F(f'Coaching: {pct(coached)} of reps coached at {cpd:.1f} calls per coaching day.'))
    if fl and fl['avg'] < TH['field']:
        co.append(F(f'DM field days {pct(fl["avg"])} of target in {field_months[-1]} ({fl["low"]} of {fl["n"]} DMs below 70%).'))
        qs.append('Which DMs are below 70% field days, and what is taking them out of the field?')
    if hc and res_ytd:
        rate = res_ytd / (hc + res_ytd)
        if rate > 0.08:
            co.append(F(f'People: {res_ytd} resignations YTD ({exe_periods[0]}–{exe_periods[-1]}) on {hc} active reps now.'))
            qs.append('What are the top exit reasons, and which vacant territories hold A-class customers?')

    # ---- IQVIA market
    if iq:
        mk.append(F(f'IQVIA YTD: Zeta share {pct(iq["shareSU"],2)} units / {pct(iq["shareV"],2)} value, vs {pct(iq["shareSUp"],2)} / {pct(iq["shareVp"],2)} last year. Value growth: market {pct(iq["mktG"],1) if iq["mktG"] is not None else "n/a"}, Zeta {pct(iq["zG"],1) if iq["zG"] is not None else "n/a"}. EVI {iq["evi"]} (units).'))
        if iq['evi'] is not None:
            dV = (iq['shareV'] or 0) - (iq['shareVp'] or 0)
            if iq['evi'] >= 105:
                st.append(F(f'Zeta grew faster than its market in IQVIA (EVI {iq["evi"]}, units share {pts((iq["shareSU"] or 0)-(iq["shareSUp"] or 0),2)} vs last year).', iq['mktV'] * dV))
            elif iq['evi'] <= 95:
                co.append(F(f'Zeta grew slower than its market in IQVIA (EVI {iq["evi"]}, units share {pts((iq["shareSU"] or 0)-(iq["shareSUp"] or 0),2)} vs last year).', iq['mktV'] * dV))
                qs.append('Which competitor is taking the share, in which market, and what is the counter-plan?')
        if iq['shareVm'] is not None and iq['shareVpm'] is not None and abs(iq['shareVm'] - iq['shareVpm']) >= 0.005:
            mk.append(F(f'Latest month: value share {pct(iq["shareVm"],2)} vs {pct(iq["shareVpm"],2)} the month before ({pts(iq["shareVm"]-iq["shareVpm"],2)}).'))
        if iq['rank'] and iq['rankP'] and iq['rank'] != iq['rankP']:
            mk.append(F(f'Zeta rank in this market: #{iq["rank"]} (last year #{iq["rankP"]}) of {iq["nCorps"]} companies.'))
        elif iq['rank']:
            mk.append(F(f'Zeta rank in this market: #{iq["rank"]} of {iq["nCorps"]} companies (unchanged).'))
        g = [x for x in iq['gainers'] if not x['zeta'] and x['dShare'] > 0.002]
        l = [x for x in iq['losers'] if not x['zeta'] and x['dShare'] < -0.002]
        if g:
            mk.append(F('Competitors gaining share: ' + ', '.join(f'{x["corp"]} {pts(x["dShare"],2)} (growth {pct(x["growth"])})' for x in g[:3]) + '.'))
        if l:
            mk.append(F('Competitors losing share: ' + ', '.join(f'{x["corp"]} {pts(x["dShare"],2)}' for x in l[:3]) + '.'))
        # sell-in vs in-market
        if ach is not None and iq['evi'] is not None and ach >= 100 and iq['evi'] < 100:
            co.append(F(f'Sell-in is {ach:.0f}% of target while IQVIA in-market sales grew slower than the market (EVI {iq["evi"]}).', ytdA - ytdO))
            qs.append('How many weeks of stock do distributors hold, and does sell-out support the sell-in trend?')
    # brand-level market comments
    bl = [b for b in brands_iq if b.get('shareP') is not None]
    for b in sorted(bl, key=lambda b: -(b['share'] - b['shareP']))[:2]:
        if b['share'] - b['shareP'] > 0.005:
            gtxt = f'growth {pct(b["growth"])}' if b['growth'] is not None else 'new in this market'
            st.append(F(f'{b["name"]} gained {pts(b["share"]-b["shareP"])} value share in {b["dm1"]} ({pct(b["shareP"],1)} → {pct(b["share"],1)}), {gtxt} vs market {pct(b["mktG"])}.', b['mktV'] * (b['share'] - b['shareP'])))
    for b in sorted(bl, key=lambda b: (b['share'] - b['shareP']))[:3]:
        if b['share'] - b['shareP'] < -0.005:
            who = b.get('topGainer')
            extra = f'; biggest gainer in that market: {who["prod"]} ({who["corp"]}) {pts(who["share"]-who["shareP"])}' if who else ''
            co.append(F(f'{b["name"]} lost {pts(b["shareP"]-b["share"])[1:]} value share in {b["dm1"]} ({pct(b["shareP"],1)} → {pct(b["share"],1)}){extra}.', b['mktV'] * (b['share'] - b['shareP'])))
            qs.append(f'What is the plan to win back share for {b["name"]} in {b["dm1"]}?')

    # new competitors in Zeta brands' markets
    seen_ne = set()
    for b in brands_iq:
        for ne in b.get('newEntrants') or []:
            k = (ne['prod'], b['dm1'])
            if k in seen_ne:
                continue
            seen_ne.add(k)
            mk.append(F(f'New competitor in {b["dm1"]} ({b["name"]}\'s market): {ne["prod"]} ({ne["corp"]}) reached {pct(ne["share"],1)} value share YTD with no sales in the same months last year.', b['mktV'] * ne['share']))
            qs.append(f'How is {b["name"]} responding to the launch of {ne["prod"]} ({ne["corp"]})?')
    # volume vs price/mix split of the YTD gap
    vol, prc, oth = sum(S['mVol']), sum(S['mPrice']), sum(S['mOther'])
    gap = ytdA - ytdO
    if ytdO and abs(gap) > 0.02 * ytdO and (vol or prc) and ach is not None:
        ytd_item['text'] += (f' Split: volume (units) {vol/1e6:+.1f}M, price/mix {prc/1e6:+.1f}M'
                             + (f', months without unit targets {oth/1e6:+.1f}M' if abs(oth) >= 0.05e6 else '') + '.')
    # sell-in vs IQVIA in-market by brand (company level, mapped brands only)
    for g in E.get('sellout') or []:
        # small bases give meaningless % (e.g. launches): need >= 0.25M/month in both sources
        if g['ytdSi'] < 1e6 or g['siChg'] is None or g['imChg'] is None or g['siBase'] < 250e3 or g['imBase'] < 250e3:
            continue
        diff = g['siChg'] - g['imChg']
        if abs(diff) >= 0.20:
            rb, re_ = g['baseMonths'], g['recentMonths']
            txt = (f'{g["name"]}: sell-in {MON[int(re_[0][5:])]}–{MON[int(re_[-1][5:])]} {g["siChg"]*100:+.0f}% vs the {MON[int(rb[0][5:])]}–{MON[int(rb[1][5:])]} monthly average; '
                   f'IQVIA in-market {g["imChg"]*100:+.0f}% over the same months (IQVIA: {", ".join(g["iqvia"])}).')
            imp = 2 * (g['siRecent'] - g['siBase'] * (1 + g['imChg']))
            mk.append(F(txt, imp))
            if diff > 0:
                qs.append(f'What is the distributor stock position for {g["name"]}, given sell-in grew faster than IQVIA in-market?')
    # customer base
    CU = E.get('customers')
    if CU and CU['total']:
        c, v = CU['counts'], CU['values']
        active = c['New'] + c['Retained'] + c['Reactivated']
        txt = (f'Customers (pharmacies) buying these products in {MON[int(sales_months[-1][5:])]}: {active:,} '
               f'({c["Retained"]:,} retained, {c["Reactivated"]:,} reactivated, {c["New"]:,} new); '
               f'{c["Lost"]:,} bought in {MON[int(sales_months[-2][5:])]} but not in {MON[int(sales_months[-1][5:])]} (their YTD value {v["Lost"]/1e6:.1f}M).')
        (co if c['Lost'] > c['New'] + c['Reactivated'] else st).append(F(txt, v['Lost']))
        if c['Lost'] > c['New'] + c['Reactivated']:
            qs.append(f'What is the plan to win back the {c["Lost"]:,} pharmacies that bought in {MON[int(sales_months[-2][5:])]} but not in {MON[int(sales_months[-1][5:])]}?')

    # full-year landing
    LD = E.get('landing')
    if LD and LD['fy']:
        need = LD['required']; gapfy = LD['landing'] - LD['fy']
        pm = LD['paceMonths']; nxt = int(sales_months[-1][5:]) + 1
        pace_lbl = f'{MON[int(pm[0][5:])]}–{MON[int(pm[-1][5:])]}'; rem_lbl = f'{MON[nxt]}–Dec' if nxt < 12 else 'Dec'
        txt = (f'Full year: at the {pace_lbl} pace ({LD["pace"]/1e6:.1f}M a month) the year closes at {LD["landing"]/1e6:.1f}M vs the {LD["fy"]/1e6:.1f}M target ({100*LD["landing"]/LD["fy"]:.0f}%). '
               f'Reaching the target needs {need/1e6:.1f}M a month for {rem_lbl} ({(need/LD["pace"]-1)*100:+.0f}% vs the current pace).')
        (st if gapfy >= 0 else co).append(F(txt, gapfy))
        if gapfy < 0:
            qs.append(f'What is the month-by-month plan to deliver {need/1e6:.1f}M a month from {MON[nxt]}?')

    # rank by EGP at stake (largest first); items without an EGP value keep their order after them
    def rank(items):
        with_imp = sorted([x for x in items if x.get('impact')], key=lambda x: -x['impact'])
        return with_imp + [x for x in items if not x.get('impact')]
    st, co = rank(st), rank(co)
    mk = mk[:1] + rank(mk[1:])

    # headline
    parts = []
    if ach is not None:
        parts.append(f'{name} closed Jan–{MON[int(sales_months[-1][5:])]} YTD at {ach:.0f}% of Official target ({ytdA/1e6:.1f}M)')
    if iq and iq['evi'] is not None:
        parts.append(f'{"gaining" if iq["evi"] >= 100 else "losing"} ground in IQVIA (EVI {iq["evi"]}, share {pts((iq["shareSU"] or 0)-(iq["shareSUp"] or 0),2)})')
    if cov is not None:
        parts.append(f'execution at {pct(cov)} coverage / {pct(rf)} Right Frequency vs the 90/80 bar')
    headline = ', '.join(parts) + '.'
    # dedupe questions, keep order
    seen = set(); qd = []
    for q in qs:
        if q not in seen:
            seen.add(q); qd.append(q)
    return {'headline': headline, 'strengths': st, 'concerns': co, 'market': mk, 'questions': qd[:8]}


# ============================================================ MAIN
def main():
    t0 = datetime.datetime.now()
    sales = build_sales()
    exe = build_execution()
    mgr = build_managers(sales['months'])
    iq = build_iqvia()
    iq_mat = build_iqvia('MAT')
    fy_targets = build_fy_targets()
    bmap = build_brand_map(sales, iq)
    sellout = sellout_groups(bmap, sales, iq)
    cust, cust_months = build_customers()
    entities = collections.OrderedDict()
    scopes = [('ALL', 'All BUs', 'all', ALL_LINES)]
    for b, ls in BU_LINES.items():
        scopes.append(('BU:' + b, b + ' BU', 'bu', ls))
    for ln in ALL_LINES:
        scopes.append(('LINE:' + ln, ln, 'line', [ln]))
    for key, name, kind, ls in scopes:
        E = roll(ls, sales, exe, mgr)
        E['landing'] = landing(E, ls, kind, fy_targets, sales['months'])
        E['sellout'] = [g for g in sellout if kind == 'all' or set(g['lines']) & set(ls)]
        E['customers'] = customers_for(key, kind, ls, cust)
        iq_e = iq['entities'].get(key)
        iq_m = iq_mat['entities'].get(key) if iq_mat else None
        # Zeta brands belonging to this scope (by IQVIA line tag)
        iq_lines = {IQ_LINE_OF.get(l, l) for l in ls}
        bl = []
        for pname, b in iq['brands'].items():
            if b['line'] in iq_lines:
                bl.append(dict(b, name=pname))
        bl.sort(key=lambda b: -b['v'])
        blm = sorted([dict(b, name=pn) for pn, b in (iq_mat['brands'] if iq_mat else {}).items() if b['line'] in iq_lines], key=lambda b: -b['v'])
        sales_brands = []
        for l in ls:
            if kind != 'line' and l in NOT_IN_BU_TOTAL:
                continue
            for r in sales['brands'].get(l, []):
                sales_brands.append(dict(r, line=l))
        sales_brands.sort(key=lambda r: -r['ytdA'])
        entities[key] = {
            'key': key, 'name': name, 'kind': kind, 'lines': ls, 'bu': LINE_BU.get(ls[0]) if kind == 'line' else (key[3:] if kind == 'bu' else None),
            'sales': E['sales'], 'exec': E['exec'], 'coach': E['coach'], 'field': E['field'], 'resignedYtd': E['resignedYtd'],
            'landing': E['landing'], 'sellout': E['sellout'], 'customers': E['customers'],
            'iqvia': iq_e, 'iqBrands': bl, 'iqviaMat': iq_m, 'iqBrandsMat': blm, 'salesBrands': sales_brands,
            'comments': comments(name, kind, E, sales['months'], exe['periods'], mgr['coachMonths'], mgr['fieldMonths'], iq_e, bl,
                                 sales['brands'], ls),
        }
    acts, act_file = build_actions(entities, sales['months'][-1])
    for k, e in entities.items():
        names = {e['name']} | ({DATA_LINE for DATA_LINE in e['lines']} if e['kind'] != 'line' else set())
        if e['kind'] == 'all':
            e['actions'] = acts
        else:
            e['actions'] = [a for a in acts if a['scope'] in names]
    mapped_sales = {b for g in bmap['groups'] for b in g['sales']}
    for k, e in entities.items():
        e['gaps'] = data_gaps(e, e['kind'], e['lines'], sales, exe['periods'], e['iqvia'], bmap, mapped_sales, e['actions'], sales['months'])
    out = {
        'meta': {'schemaVersion': SCHEMA_VERSION, 'generatedAt': datetime.datetime.now().isoformat(timespec='seconds'),
                 'salesMonths': sales['months'], 'execPeriods': exe['periods'], 'coachMonths': mgr['coachMonths'],
                 'fieldMonths': mgr['fieldMonths'], 'iqviaPeriod': iq['period'], 'iqviaYtdMonths': iq['ytdMonths'],
                 'iqviaMat': {'cur': [iq_mat['curPeriods'][0], iq_mat['curPeriods'][-1]], 'prev': [iq_mat['prevPeriods'][0], iq_mat['prevPeriods'][-1]]} if iq_mat else None,
                 'thresholds': TH, 'buLines': BU_LINES,
                 'brandMap': {'file': bmap['file'], 'review': bmap['review'], 'unmapped': bmap['unmapped'], 'groups': len(bmap['groups'])},
                 'actionsFile': act_file, 'customerMonths': cust_months, 'salesPriorYear': None,
                 'rules': 'Sales: Official target, Tender excluded, CHC BU = CHC line. Execution: Coverage-page rule (active, sick-leave exempt excluded, prorated frequency). IQVIA: OTHER MARKET excluded, Zeta = ZETA PHARM*, BU/line market = rows tagged to it, brand market = main DM1, YTD vs same months prior year. Share headline in units (as the Executive card), value share alongside.'},
        'entities': entities,
    }
    js = json.dumps(out, separators=(',', ':'), default=lambda o: None)
    with open(os.path.join(CACHE, 'business_review.json'), 'w', encoding='utf-8') as f:
        f.write(js)
    b64 = base64.b64encode(gzip.compress(js.encode('utf-8'))).decode('ascii')
    with open(os.path.join(CACHE, 'business_review.data.js'), 'w', encoding='utf-8') as f:
        f.write('window.BUSINESS_REVIEW_CACHE = {b64Data:"' + b64 + '"};\n')
    log(f'wrote business_review.json ({len(js)/1e6:.2f} MB) and business_review.data.js ({len(b64)/1e6:.2f} MB) in {(datetime.datetime.now()-t0).seconds}s')


if __name__ == '__main__':
    main()
